baseURL = "https://jjlinux.tk/"
disableKinds = ["taxonomy", "taxonomyTerm"]
enableGitInfo = true
enableRobotsTXT = true
introDescription = "JJ Linux Is a linux distro designed for speed, efficiency, and ease of use."
theme = "compose"
title = "JJ Linux"
[markup.goldmark.extensions]
typographer = false
[markup.goldmark.renderer]
unsafe = true
[markup.highlight]
codeFences = true
guessSyntax = false
hl_Lines = ""
lineNoStart = 1
lineNos = true
lineNumbersInTable = true
noClasses = false
style = "monokai"
tabWidth = 2
[markup.tableOfContents]
endLevel = 4
ordered = false
startLevel = 2
[[menu.main]]
name = "Docs"
url = "docs/"
weight = 1
[params]
author = "JJ Linux Team"
enableDarkMode = true
repo = "https://github.com/onweru/compose"
searchPlaceholder = "Search the docs ..."
time_format_blog = "Monday, January 02, 2006"
time_format_default = "January 2, 2006"
[params.logo]
darkMode = "compose-light.png"
lightMode = "compose.png"
[params.source]
icon = "github.svg"
name = "GitHub"
url = "https://github.com/JJ-OS/"
